### ISSUE TITLE
macos support

### ISSUE THREAD

**Issue by ahoarau** [biojppm/cmake#1]
Hello,
I'm facing an issue with `c4Project.cmake`
https://github.com/biojppm/cmake/blob/master/c4Project.cmake#L1843

it says "not implemented" and stops the cmake configuration. Any reasons why it is not compatible with macos ? 
I'm on `cmake 3.17.2`

**Comment by biojppm** [comment]
@ahoarau Thanks for reporting, and sorry for the late reply. Amazingly, Github does not send notifications when a bug report is created on my own repos. I've enabled all the notification setttings but had no luck. I will have to contact their customer service to sort this out.

Anyway, to the problem. (The link you posted is not permanent and the code has drifted in the meantime, but I assume [you're talking about this line](https://github.com/biojppm/cmake/blob/e05b5c742104a237977e6082cde34a2c765f9838/c4Project.cmake#L1917)). That line is there because I have no access to Apple hardware to test this on, and even if I tested on a VM, I'm not that used to with MacOS to make sure it works right.

Can you try something like this and confirm if it works?

```cmake
    if(WIN32)
        __c4_install_exports(cmake/ "..")
    elseif(APPLE)
        __c4_install_exports(${_ARCHIVE_INSTALL_DIR}/${_c4_prefix}.framework/Resources "../../..")
    elseif(UNIX)
        __c4_install_exports(${_ARCHIVE_INSTALL_DIR}/cmake/${_c4_prefix} "../../..")
    # ....
```

Please let me know if it works for you, so that I can push it to the repo.

**Comment by biojppm** [comment]
@ahoarau Can you verify?

**Comment by ahoarau** [comment]
Interestingly I did not see this Aug24 notification either. I'll try on my HW. In the meantime you could probably setup github actions in no time to test on macos. Thanks for the follow up !

**Comment by ahoarau** [comment]
And it was probably this line : 
![image](https://user-images.githubusercontent.com/703240/94900245-f8c0fc00-0494-11eb-8174-af0ab9cce78b.png)

**Comment by biojppm** [comment]
The current version is now working, including in the full test suite for c4core, of which a couple of tests suite do an install and subsequent consume of the project: eg https://github.com/biojppm/c4core/pull/23/checks?check_run_id=1300678500 . 

@ahoarau Can you confirm this works for you?

**Comment by ahoarau** [comment]
Strange I'm having 
```
CMake Error at CMakeLists.txt:6 (c4_declare_project):
  Unknown CMake command "c4_declare_project".
```
I think I'm missing some dep. rapidyaml master + c4core on pack branch + cmake on 
bc83cfc ?
Good job on the actions though

**Comment by biojppm** [comment]
This was a merge request. It has since been merged, so you can try now.

**Comment by biojppm** [comment]
MacOS is now covered in actions in c4core and rapidyaml, so I'm closing this. Feel free to reopen if something's still not working right.

**Comment by ahoarau** [comment]
👍  Thanks !
